### ISSUE TITLE
[BUG] Unable to add additional notifications

### ISSUE THREAD

**Issue by FrickDude** [StockDrops/OpenStockApp#5]
**Describe the bug**
After first adding notifications successfully and having an "Action on Notification" to choose from then navigating out of the notification hamburger menu you can see them added successfully. Then when you go back and try to add notifications again, the "Action on Notification" is blank, and no option is present in the drop down shown in screenshot 2. This keeps the notification from being added at all. I think this is a bug since you should be able to navigate back and forth through the app and add notifications any time.
![image](https://user-images.githubusercontent.com/100090854/162649198-a63d1e66-eac6-4eda-b1ba-0dc8bbcd025a.png)
![image](https://user-images.githubusercontent.com/100090854/162649285-71e57a21-17d5-4017-b202-5dbae868548d.png)

**Desktop (please complete the following information):**
 - Win 10 21H2
 - Microsoft Edge
 - Version 100.0.1185.36 (Official build) (64-bit)

**Comment by emorell96** [comment]
I was able to reproduce this and I believe the last commit will fix this issue permanently. It will be included with v1.1.1 that will release once I fix another small bug. Thanks for the report!
